#!/usr/bin/env python3
"""Generate complete runtime presentation specs for all 165 Gen 1 moves."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


BLOCK_RE = re.compile(
    r"^  ([A-Z0-9_]+) = \{\n(.*?)(?=^  [A-Z0-9_]+ = \{|^\})",
    re.M | re.S,
)


def field(body: str, name: str):
    match = re.search(
        rf'^    {re.escape(name)} = (?:(\d+)|"([^"]*)"),', body, re.M
    )
    if not match:
        raise ValueError(f"missing {name}")
    return match.group(2) if match.group(2) is not None else int(match.group(1))


def parse_moves(path: Path) -> list[dict[str, object]]:
    rows = []
    for key, body in BLOCK_RE.findall(path.read_text(encoding="utf-8")):
        rows.append(
            {
                "id": field(body, "index"),
                "key": key,
                "name": field(body, "name").title(),
                "type": field(body, "type").replace("_TYPE", ""),
                "power": field(body, "power"),
                "effect": field(body, "effect"),
            }
        )
    rows.sort(key=lambda row: row["id"])
    if [row["id"] for row in rows] != list(range(1, 166)):
        raise ValueError("generated move data is not the complete Gen 1 roster")
    return rows


SELF_EFFECTS = (
    "_UP", "HEAL_EFFECT", "FOCUS_ENERGY", "BIDE", "RAGE", "MIST",
    "LIGHT_SCREEN", "REFLECT", "SUBSTITUTE", "CONVERSION", "TRANSFORM",
    "METRONOME", "MIMIC", "MIRROR_MOVE", "SPLASH",
)
SCREEN_EFFECTS = ("HAZE", "LIGHT_SCREEN", "REFLECT", "MIST", "EXPLODE")
BEAMS = {
    "AURORA_BEAM", "BUBBLEBEAM", "HYPER_BEAM", "ICE_BEAM", "PSYBEAM",
    "SOLARBEAM", "THUNDERBOLT",
}
PROJECTILES = {
    "ACID", "BONE_CLUB", "BONEMERANG", "EGG_BOMB", "EMBER", "FIRE_BLAST",
    "LEECH_SEED", "PAY_DAY", "PIN_MISSILE", "POISON_STING", "PSYWAVE",
    "RAZOR_LEAF", "ROCK_SLIDE", "ROCK_THROW", "SEED_BOMB", "SLUDGE",
    "SONICBOOM", "SPIKE_CANNON", "SWIFT", "WATER_GUN",
}


def presentation(row: dict[str, object]) -> dict[str, object]:
    key, effect, power = row["key"], row["effect"], row["power"]
    status = power == 0
    if "EXPLODE" in effect:
        delivery, anchor = "screen", "attacker"
    elif status:
        delivery = "screen" if any(x in effect for x in SCREEN_EFFECTS) else "status"
        anchor = "attacker" if any(x in effect for x in SELF_EFFECTS) else "target"
    elif key in BEAMS or "HYPER_BEAM" in effect:
        delivery, anchor = "beam", "target"
    elif key in PROJECTILES or row["type"] not in {"NORMAL", "FIGHTING", "FLYING"}:
        delivery, anchor = "projectile", "target"
    else:
        delivery, anchor = "contact", "target"

    hits = 1
    if "ATTACK_TWICE" in effect or "TWINEEDLE" in effect:
        hits = 2
    elif "TWO_TO_FIVE" in effect:
        hits = 4
    elif "TRAPPING" in effect:
        hits = 3
    impact_at = 38 if delivery == "contact" else 46
    if delivery in {"status", "screen"}:
        impact_at = 28
    duration = impact_at + 34 + (hits - 1) * 10
    if "CHARGE" in effect or "FLY_EFFECT" in effect or "HYPER_BEAM" in effect:
        duration += 24
    if "EXPLODE" in effect:
        duration = 110
    return {
        **row,
        "kind": "generic",
        "delivery": delivery,
        "anchor": anchor,
        "hits": hits,
        "impactAt": impact_at,
        "duration": duration,
    }


def lua_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_lua(path: Path, rows: list[dict[str, object]]) -> None:
    lines = [
        "-- Generated by tools/build_all_move_specs.py. Do not edit by hand.",
        "-- Complete Gen 1 presentation fallback; exact traced specs override it.",
        "return {",
    ]
    for source in rows:
        row = presentation(source)
        lines.extend(
            [
                "  { "
                f"id = {row['id']}, key = {lua_string(row['key'])}, "
                f"name = {lua_string(row['name'])}, type = {lua_string(row['type'])},",
                "    "
                f"power = {row['power']}, effect = {lua_string(row['effect'])}, "
                f"kind = {lua_string(row['kind'])},",
                "    "
                f"delivery = {lua_string(row['delivery'])}, anchor = {lua_string(row['anchor'])}, "
                f"hits = {row['hits']},",
                "    "
                f"impactAt = {row['impactAt']}, duration = {row['duration']}, "
                "resources = {}, assets = {} },",
            ]
        )
    lines.extend(["}", ""])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--moves", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    rows = parse_moves(args.moves)
    write_lua(args.output, rows)
    print(f"generated {len(rows)} complete move specs")


if __name__ == "__main__":
    main()
