#!/usr/bin/env python3
"""Compile extracted Stadium scheduler records into a compact Lua module."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def lua(value: object, indent: int = 0) -> str:
    pad = "  " * indent
    if value is None:
        return "nil"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, list):
        if not value:
            return "{}"
        return "{\n" + ",\n".join(
            "  " * (indent + 1) + lua(item, indent + 1) for item in value
        ) + "\n" + pad + "}"
    if isinstance(value, dict):
        if not value:
            return "{}"
        rows = []
        for key, item in value.items():
            label = key if isinstance(key, str) and key.isidentifier() else f"[{lua(key)}]"
            rows.append("  " * (indent + 1) + f"{label} = {lua(item, indent + 1)}")
        return "{\n" + ",\n".join(rows) + "\n" + pad + "}"
    raise TypeError(type(value).__name__)


EVENT_FIELDS = (
    "at", "interval", "repeats", "callback", "particleCount", "batchSize",
    "anchorMode", "attachment", "aux", "aux2", "renderPreset",
    "particlePreset", "helper", "order",
)


def compile_data(source: dict[str, object]) -> dict[str, object]:
    programs = {}
    for key, program in source["programs"].items():
        programs[key] = {
            "channel": program["channel"],
            "opcode": program["opcode"],
            "assetSlots": program["assetSlots"],
            "events": [
                {field: event.get(field) for field in EVENT_FIELDS
                 if event.get(field) is not None}
                for event in program["nativeEvents"]
            ],
        }
    moves = {}
    for move in source["moves"]:
        moves[move["id"]] = {
            "key": move["key"],
            "primary": [f"primary:0x{opcode:02X}" for opcode in move["primary"]],
            "alternate": [f"primary:0x{opcode:02X}" for opcode in move["alternate"]],
            "impact": [f"impact:0x{opcode:02X}" for opcode in move["impact"]],
        }
    render_presets = {row["index"]: row for row in source.get("renderPresets", [])}
    particle_presets = {
        row["index"]: row for row in source.get("particlePresets", [])
    }
    return {
        "schema": source["schema"],
        "sourceRevision": source["sourceRevision"],
        "moves": moves,
        "programs": programs,
        "renderPresets": render_presets,
        "particlePresets": particle_presets,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    data = compile_data(json.loads(args.input.read_text(encoding="utf-8")))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        "-- Generated by tools/build_native_program_lua.py.\n"
        "-- Exact fragment-62 scheduler records; do not hand-edit.\n\n"
        "return " + lua(data) + "\n",
        encoding="utf-8",
    )
    event_count = sum(len(program["events"]) for program in data["programs"].values())
    print(f"wrote {len(data['moves'])} moves and {event_count} native events")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
