#!/usr/bin/env python3
"""Generate the Gen 1 Stadium move dispatch/resource inventory.

The input is pret/pokestadium's fragment62_315D50.c plus Gen1Recomp's ROM
manifest.  The generated Lua table is data only; it does not copy Stadium
assets and it is safe to ship with the mod.
"""

from __future__ import annotations

import argparse
import json
import re
from collections import Counter
from pathlib import Path


ARRAY_RE = re.compile(
    r"static\s+u8\s+(D_[0-9A-Fa-f]+)\[\]\s*=\s*\{(.*?)\};", re.S
)
ROW_RE = re.compile(
    r"\{\s*(D_[0-9A-Fa-f]+)\s*,\s*(D_[0-9A-Fa-f]+)\s*,\s*"
    r"(D_[0-9A-Fa-f]+)\s*,\s*(D_[0-9A-Fa-f]+)\s*,\s*"
    r"(D_[0-9A-Fa-f]+)\s*,\s*\}",
    re.S,
)


def parse_arrays(source: str) -> dict[str, list[int]]:
    arrays: dict[str, list[int]] = {}
    for name, body in ARRAY_RE.findall(source):
        arrays[name] = [int(token, 16) for token in re.findall(r"0x([0-9A-Fa-f]+)", body)]
    return arrays


def terminated(values: list[int], marker: int) -> list[int]:
    try:
        return values[: values.index(marker)]
    except ValueError as exc:
        raise ValueError(f"missing 0x{marker:02X} terminator in {values!r}") from exc


def parse_rows(source: str) -> list[tuple[str, str, str, str, str]]:
    match = re.search(
        r"static\s+u8\*\s+D_84386E08\[\]\[5\]\s*=\s*\{(.*?)\n\};",
        source,
        re.S,
    )
    if not match:
        raise ValueError("could not find D_84386E08 move table")
    rows = ROW_RE.findall(match.group(1))
    if len(rows) != 166:
        raise ValueError(f"expected null row plus 165 Gen 1 moves, found {len(rows)}")
    return rows


def load_move_names(manifest_path: Path) -> list[str]:
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    names = manifest["constants"]["moveOrder"]
    if len(names) != 165:
        raise ValueError(f"expected 165 move names, found {len(names)}")
    return names


def display_name(key: str) -> str:
    aliases = {
        "DOUBLESLAP": "Double Slap",
        "SONICBOOM": "Sonic Boom",
        "SOLARBEAM": "Solar Beam",
        "THUNDERSHOCK": "Thunder Shock",
        "POISONPOWDER": "Poison Powder",
        "PSYCHIC_M": "Psychic",
    }
    return aliases.get(key, key.replace("_", " ").title())


def build_roster(source: str, names: list[str]) -> list[dict[str, object]]:
    arrays = parse_arrays(source)
    rows = parse_rows(source)
    roster = []
    for move_id, key in enumerate(names, 1):
        symbols = rows[move_id]
        try:
            values = [arrays[symbol] for symbol in symbols]
        except KeyError as exc:
            raise ValueError(f"move {move_id} references unknown array {exc.args[0]}") from exc
        roster.append(
            {
                "id": move_id,
                "key": key,
                "name": display_name(key),
                "primary": terminated(values[0], 0),
                "alternate": terminated(values[1], 0),
                "impact": terminated(values[2], 0),
                "primaryResources": terminated(values[3], 0x3F),
                "impactResources": terminated(values[4], 0x3F),
                "sourceArrays": list(symbols),
            }
        )
    return roster


def lua_values(values: list[int]) -> str:
    return "{ " + ", ".join(f"0x{x:02X}" for x in values) + " }"


def write_lua(path: Path, roster: list[dict[str, object]]) -> None:
    lines = [
        "-- Generated by tools/build_move_roster.py. Do not edit by hand.",
        "-- Source: Pokemon Stadium fragment 62 D_84386E08.",
        "local moves = {",
    ]
    for move in roster:
        lines.extend(
            [
                f"  [{move['id']}] = {{ key = {json.dumps(move['key'])}, name = {json.dumps(move['name'])},",
                f"    primary = {lua_values(move['primary'])}, alternate = {lua_values(move['alternate'])},",
                f"    impact = {lua_values(move['impact'])},",
                f"    primaryResources = {lua_values(move['primaryResources'])},",
                f"    impactResources = {lua_values(move['impactResources'])} }},",
            ]
        )
    lines.extend(["}", "", "return moves", ""])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def sequence_key(values: list[int]) -> str:
    return "+".join(f"{x:02X}" for x in values) if values else "none"


def write_report(path: Path, roster: list[dict[str, object]]) -> None:
    primary = Counter(sequence_key(m["primary"]) for m in roster)
    impact = Counter(sequence_key(m["impact"]) for m in roster)
    resource_sets = Counter(
        sequence_key(sorted(set(m["primaryResources"] + m["impactResources"])))
        for m in roster
    )
    body_only = [m for m in roster if not m["primary"] and not m["impact"]]
    unique_resources = sorted(
        {value for m in roster for value in m["primaryResources"] + m["impactResources"]}
    )
    lines = [
        "# Stadium Gen 1 move roster",
        "",
        "Generated from Stadium's `D_84386E08` dispatch table. Move IDs and names come from Gen1Recomp's Yellow manifest.",
        "",
        f"- Moves: {len(roster)}",
        f"- Unique primary programs: {len(primary)}",
        f"- Unique impact programs: {len(impact)}",
        f"- Resource archive members referenced: {len(unique_resources)} (`{', '.join(f'0x{x:02X}' for x in unique_resources)}`)",
        f"- Body/model-only entries (no primary or impact effect program): {len(body_only)}",
        "",
        "## Highest-coverage program families",
        "",
        "| Stage | Opcode sequence | Moves |",
        "|---|---:|---:|",
    ]
    for label, counts in (("Primary", primary), ("Impact", impact)):
        for seq, count in counts.most_common(15):
            lines.append(f"| {label} | `{seq}` | {count} |")
    lines.extend(
        [
            "",
            "## Body/model-only moves",
            "",
            ", ".join(f"{m['id']} {m['name']}" for m in body_only) or "None",
            "",
            "## Full dispatch inventory",
            "",
            "| ID | Move | Primary | Alternate | Impact | Resources |",
            "|---:|---|---:|---:|---:|---:|",
        ]
    )
    for move in roster:
        resources = sorted(set(move["primaryResources"] + move["impactResources"]))
        lines.append(
            f"| {move['id']} | {move['name']} | `{sequence_key(move['primary'])}` | "
            f"`{sequence_key(move['alternate'])}` | `{sequence_key(move['impact'])}` | "
            f"`{sequence_key(resources)}` |"
        )
    lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--stadium-source", type=Path, required=True)
    parser.add_argument("--gen1-manifest", type=Path, required=True)
    parser.add_argument("--lua", type=Path, required=True)
    parser.add_argument("--report", type=Path, required=True)
    args = parser.parse_args()
    source = args.stadium_source.read_text(encoding="utf-8")
    roster = build_roster(source, load_move_names(args.gen1_manifest))
    write_lua(args.lua, roster)
    write_report(args.report, roster)
    print(f"generated {len(roster)} moves")


if __name__ == "__main__":
    main()
